using SymbolicUtils: IRStructure, populate_ir!
using Dictionaries

# NOTE:
# Dictionaries.Dictionary is an ordered container, and allows checkpointing its state by
# caching the length of the Dictionary at that point. This allows efficiently implementing
# scoping behavior, for example for loop-local CSE variables.

"""
    $TYPEDEF

Struct used for efficient codegen when coupled with a [`SymbolicUtils.IRStructure`](@ref).
Rewrites can be accessed using `.rewrites`, similar to `NameState`.

## Extended help

The following is an implementation detail and not public API.

### Fields

$TYPEDFIELDS
"""
mutable struct CodegenState{T}
    """
    The expression used as a result when codegen is finished.
    """
    const expr::Expr
    """
    An `Expr(:block)` that aliases some part of `expr`. All generated expressions are
    written to this block.
    """
    const block::Expr
    """
    The underlying `IRStructure`.
    """
    const ir::IRStructure{T}
    """
    A cache from indices of `ir` to the LHS of the assignment statement (name of the
    identifier) where it is calculated. For example, the expression `x + y` may be calculated
    as
    ```julia
    var"%1" = x
    var"%2" = y
    var"%3" = var"%1" + var"%2"
    ```
    In such a case, if we assume that the index of `x + y` in `ir` is `4`, then
    `cache[4] == Symbol("%3")`.
    """
    const cache::Dictionary{Int, Symbol}
    """
    Rewrite rules, similar to `NameState`.
    """
    const rewrites::Dict{Any, Any}
    misc_idx::Int

    function CodegenState{T}(expr, block, ir, cache, rewrites, misc_idx) where {T}
        # Verify that `block` is an `Expr(:block)`.
        @assert Meta.isexpr(block, :block)
        new{T}(expr, block, ir, cache, rewrites, misc_idx)
    end
end

"""
    $TYPEDSIGNATURES

Create a `CodegenState` where the resultant expression will be `expr`, IR will be
written to `block` and `ir` is the underlying `IRStructure`. Rewrite rules can optionally
be supplied as the last argument.
"""
function CodegenState(expr::Expr, block::Expr, ir::IRStructure{T}, rewrites = Dict()) where {T}
    CodegenState{T}(expr, block, ir, Dictionary{Int, Symbol}(), rewrites, 0)
end

"""
    $TYPEDSIGNATURES

Generate the code in `sym` for the symbolic expression at index `idx` in `cs.ir::IRStructure`.
`sym` must be an `Expr`, `Symbol`, or similar which is valid to build an expression. It must
not be or contain other symbolic expressions.

Note that this is intended to be used to generate individual atomic expressions for symbolics.
In case a symbolic requires a larger compound expression, prefer to declare intermediates
via [`SymbolicUtils.Code.declare!`](@ref) and use them here.
"""
function codegen!(cs::CodegenState, idx::Int, @nospecialize(sym))
    lhs = get_cse_name(length(cs.cache))
    push!(cs.block.args, Expr(:(=), lhs, sym))
    insert!(cs.cache, idx, lhs)
    return lhs
end

"""
    $TYPEDSIGNATURES

Declare a variable named `lhs` which is assigned the value `rhs`. This is used to declare
ephemeral intermediate values in case the generated code for a symbolic is non-trivial. To
specify generated code for a symbolic, use [`SymbolicUtils.Code.codegen!`](@ref) instead.
`rhs` has the same restrictions as `sym` in that function.

Note that all-underscore identifiers can be assigned to in Julia but not used in later
expressions. Thus side-effecting expressions (such as `setindex!`) whose result is immaterial
can be generated by setting `lhs` to `:_`. The caller is responsible for ensuring the validity
of side-effecting expressions.

This function also does not check if the same `lhs` is declared twice. The variables
declared via this function are intended as temporaries, and repeated declarations will
overwrite the previous value.
"""
function declare!(cs::CodegenState, lhs, @nospecialize(rhs))
    push!(cs.block.args, Expr(:(=), lhs, rhs))
    return lhs
end

const MISC_PREFIX = Vector{UInt8}("__miscₛᵧₘ")

"""
    $TYPEDSIGNATURES

Get a unique named miscellaneous identifier for use with [`SymbolicUtils.Code.declare!`](@ref).
"""
function get_misc_identifier(cs::CodegenState)
    name = get_numbered_symbol_with_prefix(MISC_PREFIX, cs.misc_idx)
    cs.misc_idx += 1
    return name
end

"""
    $TYPEDSIGNATURES

Get the allocator to use for a symbolic expression. If the rewrite rules contain
an entry for `ALLOCATOR_REWRITES_KEY`, will return that value and erase the rule
(since allocators cannot be reused). Otherwise, returns `default`.
"""
function get_allocator!(cs::CodegenState, @nospecialize(default))
    result = get(cs.rewrites, ALLOCATOR_REWRITES_KEY, default)
    delete!(cs.rewrites, ALLOCATOR_REWRITES_KEY)
    return result
end

const CodegenBookmarkT = Tuple{Int, SymbolicUtils.IRBookmarkT}

"""
    $TYPEDSIGNATURES

Return a bookmark for `cs`, typically used to introduce new scopes and end them via
[`SymbolicUtils.rollback!`](@ref).
"""
function SymbolicUtils.bookmark(cs::CodegenState)
    return (isempty(cs.cache) ? 0 : lastindex(cs.cache), SymbolicUtils.bookmark(cs.ir))
end

"""
    $TYPEDSIGNATURES

Rollback `cs` to the state identified by `bm`. This has similar semantics to `rollback!` for
[`SymbolicUtils.IRStructure`](@ref). It is typically used for scoping in `cs`.
"""
function SymbolicUtils.rollback!(cs::CodegenState, bm::CodegenBookmarkT)
    last_cache_key, ir_bm = bm
    if iszero(last_cache_key)
        empty!(cs.cache)
    else
        k = lastindex(cs.cache)
        while k != last_cache_key
            delete!(cs.cache, k)
            k = lastindex(cs.cache)
        end
    end
    SymbolicUtils.rollback!(cs.ir, ir_bm)
    return cs
end

"""
    $TYPEDSIGNATURES

Introduce a new scope to `cs`. Some code generation paths may require inner scopes, for
example a `for` loop or `let` block. `enter_scope` can be used to introduce a new scope,
where expressions can be generated inside the block and are not accessible once the scope
is exited. This function takes the current `CodegenState`. It returns a new `CodegenState`
which contains an alias of this block and will write to it, alongside a bookmark object.
When the scope is exited, the caller is responsible for calling
[`SymbolicUtils.Code.exit_scope!`](@ref) with this returned `CodegenState` and bookmark
object.

Note that expressions generated in this scope may reference already-generated expressions
in the enclosing scope (the scope of `cs`). Calling `enter_scope` without a corresponding
`exit_scope!` is undefined behavior.
"""
function enter_scope(cs::CodegenState{T}) where {T}
    new_scope = Expr(:block)
    bm = SymbolicUtils.bookmark(cs)
    scoped_cs = CodegenState{T}(new_scope, new_scope, cs.ir, cs.cache, cs.rewrites, cs.misc_idx)
    
    return scoped_cs, bm
end

"""
    $TYPEDSIGNATURES

End a scope introduced by [`SymbolicUtils.Code.enter_scope`](@ref). This function should
be called with the `CodegenState` and bookmark object returned by that function. It will
return an `Expr(:block)` of all code generated in this scope. Additionally, any subsequent
code generation using the `CodegenState` that `cs` was created from (the `CodegenState`
passed to `enter_scope`) will not reference expressions generated in this scope.

Note that the `Expr(:block)` returned by this function is not yet added to the outer
scope. That is the responsibility of the caller. Calling `exit_scope!` twice on the same
`cs` or with the same bookmark is undefined behavior.
"""
function exit_scope!(cs::CodegenState, bm::CodegenBookmarkT)
    result = cs.block
    SymbolicUtils.rollback!(cs, bm)
    return result
end

"""
    $TYPEDSIGNATURES

Generate an expression for calling the allocator `allocator` to store the result of `expr`.
"""
function codegen_allocator_call!(
        cs::CodegenState{T}, @nospecialize(allocator), expr::BasicSymbolic{T}, expr_idx::Int
    ) where {T}
    allocator_sym::Symbol = if allocator isa BasicSymbolic{T}
        cs(allocator)
    else
        declare!(cs, get_misc_identifier(cs), allocator)
    end
    sh = shape(expr)::ShapeVecT
    sz_expr = Expr(:tuple)
    @union_split_smallvec sh for ax in sh
        push!(sz_expr.args, length(ax))
    end
    return codegen!(cs, expr_idx, Expr(:call, allocator_sym, sz_expr))
end

"""
    $TYPEDSIGNATURES

Replacement of [`SymbolicUtils.Code.toexpr`](@ref) using IR-based codegen.
"""
function fast_toexpr(sym::BasicSymbolic{T}, rewrites::Dict{Any, Any}) where {T}
    ir = IRStructure{T}()
    return fast_toexpr(sym, ir, rewrites)
end

function fast_toexpr(sym, ir::IRStructure{T}, rewrites::Dict{Any, Any}) where {T}
    expr = block = Expr(:block)
    state = CodegenState(expr, block, ir, rewrites)
    state(sym)
    return expr
end

"""
    $TYPEDSIGNATURES
"""
function fast_toexpr(sym::CodegenPrimitive, ir::IRStructure{T}, rewrites::Dict{Any, Any}) where {T}
    expr = block = Expr(:block)
    state = CodegenState(expr, block, ir, rewrites)
    lhs = state(sym)::Symbol
    for line in expr.args
        if Meta.isexpr(line, :(=)) && line.args[1] === lhs
            return line.args[2]
        end
    end
    _unreachable()
end

"""
    function codegen_function!(fn::F, cs::CodegenState{T}, expr::BasicSymbolic{T}, expr_idx::Int) where {F, T}

Generate code for `expr` whose operation is `fn` and index in `cs.ir` is `expr_idx`.
Implementers of this function should _only_ dispatch on `F`, and the rest of the types should
be as provided in the signature above.

This function should generate a Julia expression `result` for `expr`, and call
[`SymbolicUtils.Code.codegen!`](@ref)`(cs, expr_idx, result)`. Temporary intermediate values
may be declared via [`SymbolicUtils.Code.declare!`](@ref). This function should return the
value returned by `SymbolicUtils.Code.codegen!`. Any other return value is undefined behavior.

In case the code generation process here requires the results of other symbolic expressions,
it should call `cs` to obtain them. For example, if it requires the generated code for
`arguments(expr)[1]`, it should call `cs(arguments(expr)[1])` to obtain it. This will return
a `Symbol` indicating the identifier in the generated code which is assigned the requested
value.

This function is allowed to non-destructively mutate `cs.ir`. All information present in
`cs.ir` upon entry to this function should be present when it returns. The function may
add expressions to `cs.ir` and choose to use [`SymbolicUtils.rollback!`](@ref) to restore
to an earlier state, but this earlier state should not erase information that was not
added by this function.

In case the code generation process requires creating a new scope such as a `for` loop or
`let` block, it should use [`SymbolicUtils.Code.enter_scope`](@ref) and
[`SymbolicUtils.Code.exit_scope!`](@ref).

The code generation in this function does not need to handle checking if `expr` is in
`cs.rewrites`. That functionality is handled elsewhere.
"""
function codegen_function! end

function codegen_function!(::Type{ArrayOp{T}}, cs::CodegenState{T}, expr::BasicSymbolic{T}, expr_idx::Int) where {T}
    _allocator = get_allocator!(cs, zeros)
    output_buffer = codegen_allocator_call!(cs, _allocator, expr, expr_idx)
    ranges, innerexpr, output_idx = @match expr begin
        BSImpl.ArrayOp(; ranges, expr = innerexpr, output_idx) => begin
            (ranges, innerexpr, output_idx)
        end
        _ => _unreachable()
    end
    new_ranges = RangesT{T}()
    new_expr = unidealize_indices(innerexpr, ranges, new_ranges)

    scoped_cs, bm = enter_scope(cs)

    inner_result = scoped_cs(new_expr)

    loopvar_order = BasicSymbolic{T}[]

    index_expr = Expr(:call, CartesianIndex)
    @union_split_smallvec output_idx for i in output_idx
        push!(index_expr.args, scoped_cs(i))
        if i isa BasicSymbolic{T}
            push!(loopvar_order, i)
        end
    end
    reverse!(loopvar_order)
    ref_expr = Expr(:ref, output_buffer, index_expr)

    declare!(scoped_cs, :__accum, Expr(:call, :+, ref_expr, inner_result))
    declare!(scoped_cs, :_, Expr(:(=), ref_expr, :__accum))

    merge!(new_ranges, ranges)
    append!(loopvar_order, keys(new_ranges))
    unique!(loopvar_order)

    outer_expr = Expr(:block)
    cur_expr = outer_expr
    for lv in loopvar_order
        new_cur_expr = Expr(:block)
        push!(cur_expr.args, Expr(:for, Expr(:(=), scoped_cs(lv), new_ranges[lv]), new_cur_expr))
        cur_expr = new_cur_expr
    end

    scoped_block = exit_scope!(scoped_cs, bm)
    push!(cur_expr.args, scoped_block)

    declare!(cs, :_, outer_expr)

    return output_buffer
end

function write_constant_array!(cs::CodegenState{T}, vw::Symbol, val::AbstractArray) where {T}
    for (i, v) in enumerate(val)
        write_target = Expr(:ref, vw, i)
        declare!(cs, write_target, v)
    end
end

function codegen_function!(::Type{ArrayMaker{T}}, cs::CodegenState{T}, expr::BasicSymbolic{T}, expr_idx::Int) where {T}
    _allocator = get_allocator!(cs, zeros)
    output_buffer = codegen_allocator_call!(cs, _allocator, expr, expr_idx)
    regions, values = @match expr begin
        BSImpl.ArrayMaker(; regions, values) => (regions, values)
    end
    
    @union_split_smallvec regions @union_split_smallvec values begin
        for (region, val) in zip(regions, values)
            # We are writing to a single element
            if all(isone ∘ length, region)
                lhs = Expr(:ref, output_buffer)
                @union_split_smallvec region for ax in region
                    push!(lhs.args, first(ax))
                end
                rhs = cs(val[SymbolicUtils.stable_eachindex(val)[1]])
                declare!(cs, lhs, rhs)
                continue
            end
            view_expr = Expr(:call, view, output_buffer)
            @union_split_smallvec region append!(view_expr.args, region)
            vw = declare!(cs, get_misc_identifier(cs), view_expr)
            @match val begin
                # Replace the allocator. We want it to write directly to the output
                # No point constructing a new expression, just do what `with_allocator`
                # would do in `codegen_ir!`.
                BSImpl.Term(; f, args) && if f === with_allocator end => begin
                    old_allocator = add_allocator!(cs, Expr(:call, Returns, vw))
                    cs(args[2])
                    reset_allocator!(cs, old_allocator)
                end
                _ && if supports_with_allocator(val) end => begin
                    old_allocator = add_allocator!(cs, Expr(:call, Returns, vw))
                    cs(val)
                    reset_allocator!(cs, old_allocator)
                end
                BSImpl.Const(; val) => write_constant_array!(cs, vw, val)
                _ => begin
                    temp_array = cs(val)
                    declare!(cs, get_misc_identifier(cs), Expr(:call, copyto!, vw, temp_array))
                end
            end
        end
    end

    return declare!(cs, get_misc_identifier(cs), output_buffer)
end

function codegen_function!(
        ::typeof(SymbolicUtils.array_literal), cs::CodegenState{T}, expr::BasicSymbolic{T},
        expr_idx::Int
    ) where {T}
    _allocator = get_allocator!(cs, nothing)
    if _allocator === nothing
        return codegen_function_no_nanmath!(SymbolicUtils.array_literal, cs, expr, expr_idx)
    end
    output_buffer = codegen_allocator_call!(cs, _allocator, expr, expr_idx)
    args = @match expr begin
        BSImpl.Term(; args) => args
    end
    @union_split_smallvec args for (idx, arg) in enumerate(Iterators.drop(args, 1))
        declare!(cs, :_, Expr(:call, setindex!, output_buffer, cs(arg), idx))
    end

    return output_buffer
end

function codegen_function!(@nospecialize(op::Union{typeof(*), typeof(+)}), cs::CodegenState{T}, expr::BasicSymbolic{T}, expr_idx::Int) where {T}
    if get(cs.rewrites, :sort_addmul, true)::Bool
        args = parent(sorted_arguments(expr))
    else
        args = parent(arguments(expr))
    end

    if length(args) == 1
        return codegen!(cs, expr_idx, Expr(:call, op, cs(args[1])))
    end

    if symtype(expr) <: Number
        cur = Expr(:call, op, cs(args[1]), cs(args[2]))
        for i in 3:length(args)
            cur = Expr(:call, op, cur, cs(args[i]))
        end
        return codegen!(cs, expr_idx, cur)
    end

    result = Expr(:call, op)
    @union_split_smallvec args for arg in args
        push!(result.args, cs(arg))
    end
    return codegen!(cs, expr_idx, result)
end

function codegen_function!(op::typeof(^), cs::CodegenState{T}, expr::BasicSymbolic{T}, expr_idx::Int) where {T}
    base, exp = arguments(expr)
    base_sym = cs(base)
    @match exp begin
        BSImpl.Const(; val) => begin
            if val isa Real
                if _isone(val)
                    return codegen!(cs, expr_idx, base_sym)
                end
                if _isone(-val)
                    return codegen!(cs, expr_idx, Expr(:call, inv, base_sym))
                end
                if !(val isa Integer) && get(cs.rewrites, :nanmath, false)::Bool
                    op = NaNMath.pow
                end
            end
            return codegen!(cs, expr_idx, Expr(:call, op, base_sym, val))
        end
        _ => begin
            sT = symtype(exp)
            exp_sym = cs(exp)
            if get(cs.rewrites, :nanmath, false)::Bool
                return codegen!(cs, expr_idx, Expr(:call, NaNMath.pow, base_sym, exp_sym))
            else
                return codegen!(cs, expr_idx, Expr(:call, ^, base_sym, exp_sym))
            end
        end
    end
end

function codegen_function!(::typeof(ifelse), cs::CodegenState{T}, expr::BasicSymbolic{T}, expr_idx::Int) where {T}
    cond, iftrue, iffalse = arguments(expr)
    return codegen!(cs, expr_idx, Expr(:if, cs(cond), cs(iftrue), cs(iffalse)))
end

function codegen_function_no_nanmath!(@nospecialize(op), cs::CodegenState{T}, expr::BasicSymbolic{T}, expr_idx::Int) where {T}
    result = Expr(:call)
    if op isa BasicSymbolic{T}
        opsym = cs(op)
        push!(result.args, opsym)
    else
        push!(result.args, op)
    end
    args = parent(arguments(expr))
    @union_split_smallvec args for arg in args
        push!(result.args, cs(arg))
    end
    return codegen!(cs, expr_idx, result)
end

function codegen_function!(@nospecialize(op), cs::CodegenState{T}, expr::BasicSymbolic{T}, expr_idx::Int) where {T}
    # Avoid using `op in NaNMathFuns` since that is dynamic dispatch.
    # Also avoid using `nameof(op)` for the same reason.
    if !get(cs.rewrites, :nanmath, false)::Bool
        return codegen_function_no_nanmath!(op, cs, expr, expr_idx)
    elseif op === sin
        name = :sin
    elseif op === cos
        name = :cos
    elseif op === tan
        name = :tan
    elseif op === asin
        name = :asin
    elseif op === acos
        name = :acos
    elseif op === acosh
        name = :acosh
    elseif op === atanh
        name = :atanh
    elseif op === log
        name = :log
    elseif op === log2
        name = :log2
    elseif op === log10
        name = :log10
    elseif op === lgamma
        name = :lgamma
    elseif op === log1p
        name = :log1p
    elseif op === sqrt
        name = :sqrt
    else
        return codegen_function_no_nanmath!(op, cs, expr, expr_idx)
    end
    op = GlobalRef(NaNMath, name)
    return codegen_function_no_nanmath!(op, cs, expr, expr_idx)
end

function codegen_function!(::typeof(getindex), cs::CodegenState{T}, expr::BasicSymbolic{T}, expr_idx::Int) where {T}
    args = parent(arguments(expr))
    if isequal(args[1], SymbolicUtils.idxs_for_arrayop(T))
        offset = unwrap_const(args[2])::Int
        return codegen_arrayop_indexer(offset)
    end
    result = Expr(:ref)
    @union_split_smallvec args for arg in args
        push!(result.args, cs(arg))
    end
    return codegen!(cs, expr_idx, result)
end

function codegen_function!(@nospecialize(op::SymbolicUtils.Mapper), cs::CodegenState{T}, expr::BasicSymbolic{T}, expr_idx::Int) where {T}
    result = Expr(:call, map)
    fn = op.f
    if fn isa BasicSymbolic{T}
        push!(result.args, cs(fn))
    else
        push!(result.args, fn)
    end
    args = @match expr begin
        BSImpl.Term(; args) => args
    end
    @union_split_smallvec args for arg in args
        push!(result.args, cs(arg))
    end
    return codegen!(cs, expr_idx, result)
end

function codegen_function!(@nospecialize(op::SymbolicUtils.Mapreducer), cs::CodegenState{T}, expr::BasicSymbolic{T}, expr_idx::Int) where {T}
    result = Expr(:call, mapreduce)
    kws = Expr(:parameters)
    if op.dims isa Int
        dims = op.dims
        if dims isa BasicSymbolic{T}
            push!(kws.args, Expr(:kw, :dims, cs(dims)))
        else
            push!(kws.args, Expr(:kw, :dims, dims))
        end
    end
    if op.init !== nothing
        init = op.init
        if init isa BasicSymbolic{T}
            push!(kws.args, Expr(:kw, :init, cs(init)))
        else
            push!(kws.args, Expr(:kw, :init, init))
        end
    end
    if !isempty(kws.args)
        push!(result.args, kws)
    end
    fn = op.f
    if fn isa BasicSymbolic{T}
        push!(result.args, cs(fn))
    else
        push!(result.args, fn)
    end
    reducer = op.reduce
    if reducer isa BasicSymbolic{T}
        push!(result.args, cs(reducer))
    else
        push!(result.args, reducer)
    end
    args = @match expr begin
        BSImpl.Term(; args) => args
    end
    @union_split_smallvec args for arg in args
        push!(result.args, cs(arg))
    end
    return codegen!(cs, expr_idx, result)
end

function add_allocator!(cs::CodegenState, @nospecialize(alloc))
    old_allocator = get(cs.rewrites, ALLOCATOR_REWRITES_KEY, nothing)
    cs.rewrites[ALLOCATOR_REWRITES_KEY] = alloc
    return old_allocator
end

function reset_allocator!(cs::CodegenState, @nospecialize(old_alloc))
    cs.rewrites[ALLOCATOR_REWRITES_KEY] = old_alloc
    return nothing
end

function codegen_ir!(cs::CodegenState{T}, idx::Int) where {T}
    cached = get(cs.cache, idx, nothing)
    if cached isa Symbol
        return cached
    end
    ir = cs.ir
    sym = ir[idx]
    if !SymbolicUtils.isconst(sym)
        new_expr = get(cs.rewrites, sym, nothing)
        if new_expr isa BasicSymbolic{T}
            new_idx = populate_ir!(ir, new_expr)
            return codegen_ir!(cs, new_idx)
        elseif new_expr isa Expr
            return codegen!(cs, idx, new_expr)
        elseif new_expr isa Symbol
            return codegen!(cs, idx, new_expr)
        elseif new_expr !== nothing
            _unreachable()
        end
    end

    @match sym begin
        BSImpl.Const(; val) => if val isa CodegenPrimitive
            return cs(val)
        else
            return codegen!(cs, idx, val)
        end
        BSImpl.Sym(; name) => return codegen!(cs, idx, name)
        BSImpl.ArrayOp(; term) => if term isa BasicSymbolic{T}
            new_idx = populate_ir!(ir, term)
            return codegen_ir!(cs, new_idx)
        else
            return codegen_function!(ArrayOp{T}, cs, sym, idx)
        end
        BSImpl.ArrayMaker(;) => return codegen_function!(ArrayMaker{T}, cs, sym, idx)
        BSImpl.Term(; f, args) => begin
            if f === (^)
                return codegen_function!(^, cs, sym, idx)
            elseif f === ifelse
                return codegen_function!(ifelse, cs, sym, idx)
            elseif f === getindex
                return codegen_function!(getindex, cs, sym, idx)
            elseif f === with_allocator
                old_allocator = add_allocator!(cs, args[1])
                result = cs(args[2])
                reset_allocator!(cs, old_allocator)
                return result
            else
                return codegen_function!(f, cs, sym, idx)::Symbol
            end
        end
        BSImpl.Div(; num, den) => begin
            return codegen!(cs, idx, Expr(:call, /, cs(num), cs(den)))
        end
        BSImpl.AddMul(; variant) => if variant === AddMulVariant.ADD
            return codegen_function!((+), cs, sym, idx)
        else
            return codegen_function!((*), cs, sym, idx)
        end
    end
end

function (cs::CodegenState)(arr::AbstractArray)
    uarr = unwrap(arr)
    if uarr !== arr
        return cs(uarr)
    end
    return cs(MakeArray(arr, typeof(arr)))
end

function (cs::CodegenState)(arr::Union{SparseVector, SparseMatrixCSC})
    return cs(MakeSparseArray(arr))
end

function (cs::CodegenState)(@nospecialize(thing))
    uthing = unwrap(thing)
    if uthing !== thing
        return cs(uthing)
    end
    return declare!(cs, get_misc_identifier(cs), thing)
end

function (cs::CodegenState)(expr::BasicSymbolic{T})::Symbol where {T}
    idx = populate_ir!(cs.ir, expr)
    codegen_ir!(cs, idx)
end

function (cs::CodegenState)(expr::Assignment)
    lhs = manual_dispatch_toexpr(expr.lhs, NameState(cs.rewrites))
    if Meta.isexpr(lhs, :call)
        scs, bm = enter_scope(cs)
        scs(expr.rhs)
        rhs = exit_scope!(scs, bm)
    else
        rhs = cs(expr.rhs)
    end
    return declare!(cs, lhs, rhs)
end

function (cs::CodegenState{T})(l::Let) where {T}
    if all(x->x isa Assignment && !(x.lhs isa DestructuredArgs), l.pairs)
        dargs = Vector{Assignment}(l.pairs)
    else
        dargs = Assignment[]
        for x in l.pairs
            handle_let_pair!(dargs, x, cs)
        end
    end

    if l.let_block
        scs, bm = enter_scope(cs)
        for asg in dargs
            lhs = asg.lhs
            if lhs isa BasicSymbolic{T} && iscall(lhs)
                scs.rewrites[lhs] = Symbol(string(lhs)::String)
            end
            scs(asg)
        end
        bindings = exit_scope!(scs, bm)

        scs, bm = enter_scope(cs)
        scs(l.body)
        body = exit_scope!(scs, bm)
        result = Expr(:let, bindings, body)
        return declare!(cs, get_misc_identifier(cs), result)
    end
    isempty(dargs) && return cs(l.body)

    for asg in dargs
        lhs = asg.lhs
        if lhs isa BasicSymbolic{T} && iscall(lhs)
            cs.rewrites[lhs] = Symbol(string(lhs)::String)
        end
        cs(asg)
    end

    return cs(l.body)
end

function (cs::CodegenState{T})(fn::Func) where {T}
    dargs = Union{Assignment, DestructuredArgs}[]
    for arg in fn.args
        if arg isa BasicSymbolic{T}
            cs.rewrites[arg] = Symbol(string(arg)::String)
        elseif arg isa Assignment
            lhs = arg.lhs
            if lhs isa BasicSymbolic{T}
                cs.rewrites[lhs] = Symbol(string(lhs)::String)
            end
        elseif arg isa DestructuredArgs
            push!(dargs, arg)
        end
    end
    for kw in fn.kwargs
        lhs = kw.lhs
        if lhs isa BasicSymbolic{T}
            cs.rewrites[lhs] = Symbol(string(lhs)::String)
        end
    end

    scs, bm = enter_scope(cs)
    scs(Let(dargs, fn.body, false))
    body = exit_scope!(scs, bm)

    fn_args = Expr(:tuple)
    if !isempty(fn.kwargs)
        fn_kws = Expr(:parameters)
        for asg in fn.kwargs
            lhs = manual_dispatch_toexpr(asg.lhs, NameState(cs.rewrites))
            asg_cs, bm = enter_scope(cs)
            asg_cs(asg.rhs)
            rhs = exit_scope!(asg_cs, bm)
            push!(fn_kws.args, Expr(:kw, lhs, rhs))
        end
        push!(fn_args.args, fn_kws)
    end

    for arg in fn.args
        if arg isa BasicSymbolic{T}
            push!(fn_args.args, cs.rewrites[arg]::Symbol)
        elseif arg isa Assignment
            asg_cs, bm = enter_scope(cs)
            asg_cs(arg.rhs)
            rhs = exit_scope!(asg_cs, bm)
            lhs = manual_dispatch_toexpr(arg.lhs, NameState(cs.rewrites))
            push!(fn_args.args, Expr(:(=), lhs, rhs))
        elseif arg isa DestructuredArgs
            name = arg.name
            if name isa BasicSymbolic{T}
                push!(fn_args.args, manual_dispatch_toexpr(name, NameState(cs.rewrites)))
            else
                push!(fn_args.args, name::Symbol)
            end
        else
            push!(fn_args.args, manual_dispatch_toexpr(arg, NameState(cs.rewrites)))
        end
    end

    fn_body = Expr(:block)
    append!(fn_body.args, fn.pre)
    push!(fn_body.args, body)
    return declare!(cs, get_misc_identifier(cs), Expr(:function, fn_args, fn_body))
end

function (cs::CodegenState)(ex::SetArray)
    arr = cs(ex.arr)::Symbol
    lhss = []
    rhss = Symbol[]
    for (i, elem) in enumerate(ex.elems)
        if elem isa AtIndex
            push!(lhss, cs(elem.i))
            push!(rhss, cs(elem.elem))
        else
            push!(lhss, i)
            push!(rhss, cs(elem))
        end
    end

    scs, bm = enter_scope(cs)
    for (lhs, rhs) in zip(lhss, rhss)
        declare!(scs, Expr(:ref, arr, lhs), rhs)
    end
    declare!(scs, get_misc_identifier(cs), ex.return_arr ? arr : nothing)
    body = exit_scope!(scs, bm)
    if ex.inbounds
        body = Expr(:macrocall, nameof(var"@inbounds"), LineNumberNode(0), body)
    end
    return declare!(cs, get_misc_identifier(cs), body)
end

function (cs::CodegenState)(ex::MakeArray)
    _similarto = ex.similarto
    if _similarto isa Type
        similarto = cs(_similarto)
    else
        similarto = declare!(cs, get_misc_identifier(cs), Expr(:call, typeof, cs(_similarto)))
    end
    ndim = ndims(ex.elems)::Int
    elT = ex.output_eltype
    result = Expr(
        :call, create_array, similarto, elT, Expr(:call, Expr(:curly, Val, ndim)),
        Expr(:call, Expr(:curly, Val, size(ex.elems)))
    )
    for x in ex.elems
        push!(result.args, cs(x))
    end
    return declare!(cs, get_misc_identifier(cs), result)
end

function (cs::CodegenState{T})(a::MakeSparseArray{<:SparseMatrixCSC}) where {T}
    I, J, V = findnz(a.array)
    m, n = size(a.array)
    result = Expr(:call, sparse, I, J, cs(Const{T}(V)), m, n)
    return declare!(cs, get_misc_identifier(cs), result)
end

function (cs::CodegenState{T})(a::MakeSparseArray{<:SparseVector}) where {T}
    I, V = findnz(a.array)
    n = length(a.array)
    result = Expr(:call, SparseVector, n, I, cs(Const{T}(V)))
    return declare!(cs, get_misc_identifier(cs), result)
end

function (cs::CodegenState)(a::MakeTuple)
    result = Expr(:tuple)
    for ex in a.elems
        push!(result.args, cs(ex))
    end
    return declare!(cs, get_misc_identifier(cs), result)
end

function (cs::CodegenState)(ex::LiteralExpr)
    declare!(cs, get_misc_identifier(cs), recurse_expr(ex.ex, NameState(cs.rewrites)))
end

function (cs::CodegenState)(f::ForLoop)
    st = NameState(cs.rewrites)
    result = Expr(
        :for, Expr(
            :(=), manual_dispatch_toexpr(f.itervar, st), manual_dispatch_toexpr(f.range, st)
        )
    )
    scs, bm = enter_scope(cs)
    scs(f.body)
    body = exit_scope!(scs, bm)
    push!(result.args, body)
    return declare!(cs, get_misc_identifier(cs), result)
end
