name: Benchmark a pull request

on:
  pull_request_target:
    branches:
      - master
      - v4

permissions:
  pull-requests: write

jobs:
  bench:
    name: "Benchmarks"
    strategy:
      matrix:
        version:
          - "1"
          - "lts"
    runs-on: ubuntu-latest
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: "${{ matrix.version }}"
          script: "benchmark/benchmarks.jl"
